name: Publish
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: "latest"
          cabal-version: "latest"

      - run: cabal sdist
      - run: cabal haddock --haddock-for-hackage --enable-doc

      - uses: haskell-actions/hackage-publish@v1
        with:
          hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
          packagesPath: dist-newstyle/sdist/
          docsPath: dist-newstyle/
          publish: false
